-- Supabase SQL Editor ichida bir marta ishga tushiring.
create table if not exists public.users (
  user_id bigint primary key,
  phone text,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.genres (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.movies (
  code text primary key,
  message_id bigint not null,
  title text not null default '',
  genre text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.downloads (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  movie_code text not null references public.movies(code) on delete cascade,
  downloaded_at timestamptz not null default now()
);

create index if not exists downloads_user_id_idx on public.downloads(user_id);
create index if not exists downloads_movie_code_idx on public.downloads(movie_code);

-- Barcha API so'rovlari Render backenddagi service-role kaliti bilan bajariladi.
alter table public.users enable row level security;
alter table public.genres enable row level security;
alter table public.movies enable row level security;
alter table public.downloads enable row level security;
